### ISSUE TITLE
SyntaxError in topological_sort()

### ISSUE THREAD

**Issue by goldstar611** [bwhmather/ssort#21]
I feel silly posting this stack trace but I've never seen a single forward slash as a function parameter before. The change was [added 10 months back](https://github.com/bwhmather/ssort/blame/9dcbc1c1ab56a7d6644d75a731d29fcd1bbe5e9d/src/ssort/_graphs.py#L135) and CI is passing so there's something I'm missing. 

`python3 -m ssort --diff simple_file.py`
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.7/dist-packages/ssort/__init__.py", line 5, in <module>
    from ssort._ssort import ssort
  File "/usr/local/lib/python3.7/dist-packages/ssort/_ssort.py", line 4, in <module>
    from ssort._dependencies import (
  File "/usr/local/lib/python3.7/dist-packages/ssort/_dependencies.py", line 5, in <module>
    from ssort._graphs import Graph
  File "/usr/local/lib/python3.7/dist-packages/ssort/_graphs.py", line 135
    def topological_sort(target, /, *, graph=None):
                                 ^
SyntaxError: invalid syntax
```

**Comment by goldstar611** [comment]
I knew I was missing something, that syntax is for python 3.8+ which means setup.cfg is out of date, I double checked before installing from master.
https://github.com/bwhmather/ssort/blob/f1afdfa0b0721b33c040e624d72ff02e504183f9/setup.cfg#L23

**Comment by bwhmather** [comment]
Thank you for your PR.  Sorry for not keeping the version bounds in sync.

For people who stumble across this issue later I'll repeat the explanation I gave there, not that it excuses my sloppiness with `setup.cfg`:
> A more fundamental reason why `ssort` doesn't support python versions prior to 3.8 is that 3.8 is the first version where ast nodes have `end_lineno` and `end_col_offset` attributes. `ssort` relies on these to be able to cut out the right bits of code when shuffling things about.
